name: Bug report
description: Report a reproducible problem with the BYD vehicle integration.
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Please include concise details and redacted logs.

  - type: checkboxes
    id: existing
    attributes:
      label: Existing issue check
      description: Please search existing issues before submitting.
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead.
      placeholder: Tell us what happened and what you expected.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Trigger ...
        3. Observe ...
    validations:
      required: true

  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant version
      placeholder: 2026.x.x
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: Integration version
      placeholder: Version from HACS or manifest
    validations:
      required: true

  - type: input
    id: byd_region_country
    attributes:
      label: BYD app region/country
      placeholder: Example: EU / Sweden
    validations:
      required: true

  - type: textarea
    id: relevant_logs
    attributes:
      label: Relevant logs
      description: Paste relevant logs only. Remove VIN, tokens, email, and account identifiers.
      render: shell
    validations:
      required: true
